import { Technology, BuildingType, ItemType } from './types';

export interface CraftingRecipe {
  id: string;
  name: string;
  requiredTech?: string;
  inputs: Partial<Record<ItemType, number>>;
  output: ItemType;
  outputCount: number;
  timeCost: number; // in seconds/ticks
}

export interface BuildingCost {
  type: BuildingType;
  name: string;
  description: string;
  requiredTech?: string;
  inputs: Partial<Record<ItemType, number>>;
  workNeeded: number;
  maxWorkers: number;
  maxStorage: number;
  housingCapacity?: number;
  production?: {
    inputs?: Partial<Record<ItemType, number>>;
    outputs: Partial<Record<ItemType, number>>;
    interval: number; // in ticks
  };
}

export const TECHNOLOGIES: Technology[] = [
  // ERA 1: PRIMEVAL (TABULA RASA - ZERO PRE-EXISTING KNOWLEDGE)
  {
    id: 'wild_nourishment',
    name: 'Edible Berries & Flora',
    era: 'primeval',
    description: 'Inspect unknown plants and discover that colorful wild berries provide sweet sustenance.',
    icon: '🫐',
    requiredResearch: 15,
    researchProgress: 0,
    prerequisites: [],
    unlocksBuildings: [],
    unlocksItems: ['berries', 'wild_seeds'],
    discovered: false,
  },
  {
    id: 'discovery_wood',
    name: 'Discovery of Wood',
    era: 'primeval',
    description: 'Examine fallen tree branches and discover that dry wooden sticks are rigid tools and extensions of the hand.',
    icon: '🪵',
    requiredResearch: 20,
    researchProgress: 0,
    prerequisites: [],
    unlocksBuildings: [],
    unlocksItems: ['stick'],
    discovered: false,
  },
  {
    id: 'discovery_stone',
    name: 'River Stones & Rocks',
    era: 'primeval',
    description: 'Pick up smooth, heavy river pebbles and discover hard mineral rocks that do not decay.',
    icon: '🪨',
    requiredResearch: 25,
    researchProgress: 0,
    prerequisites: [],
    unlocksBuildings: [],
    unlocksItems: ['stone'],
    discovered: false,
  },
  {
    id: 'discovery_flint',
    name: 'Sharp Fracture & Flint',
    era: 'primeval',
    description: 'Accidentally crack hard rocks together and discover that mineral flint splits with razor-sharp cutting edges.',
    icon: '💎',
    requiredResearch: 35,
    researchProgress: 0,
    prerequisites: ['discovery_stone'],
    requiredItems: { stone: 1 },
    unlocksBuildings: [],
    unlocksItems: ['flint'],
    discovered: false,
  },
  {
    id: 'discovery_sparks',
    name: 'Percussion Sparks',
    era: 'primeval',
    description: 'Notice that striking flint violently against mineral rocks throws glowing, leaping sparks.',
    icon: '✨',
    requiredResearch: 45,
    researchProgress: 0,
    prerequisites: ['discovery_flint', 'discovery_stone'],
    requiredItems: { flint: 1, stone: 1 },
    unlocksBuildings: [],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'discovery_fire',
    name: 'The Discovery of Fire',
    era: 'primeval',
    description: 'Catch a spark in dry tinder, blow gently, and witness the terrifying and miraculous birth of Fire.',
    icon: '🔥',
    requiredResearch: 60,
    researchProgress: 0,
    prerequisites: ['discovery_sparks', 'discovery_wood'],
    requiredItems: { flint: 1, stick: 2 },
    unlocksBuildings: [],
    unlocksItems: ['firewood'],
    discovered: false,
  },
  {
    id: 'contained_hearth',
    name: 'Contained Campfire & Hearth',
    era: 'primeval',
    description: 'Realize that fire consumes the wild unless ringed with river stones, creating a safe radiant hearth for warmth and cooked food.',
    icon: '⛺',
    requiredResearch: 75,
    researchProgress: 0,
    prerequisites: ['discovery_fire', 'discovery_stone'],
    requiredItems: { stick: 4, stone: 4 },
    unlocksBuildings: ['campfire'],
    unlocksItems: ['cooked_food'],
    discovered: false,
  },
  {
    id: 'flint_knapping',
    name: 'Flint Knapping & Tools',
    era: 'primeval',
    description: 'Deliberately strike flint cores to knap durable chopping handaxes and spear points.',
    icon: '🪓',
    requiredResearch: 90,
    researchProgress: 0,
    prerequisites: ['discovery_flint', 'discovery_wood'],
    requiredItems: { flint: 2, stick: 2 },
    unlocksBuildings: [],
    unlocksItems: ['stone_axe', 'flint_spear'],
    discovered: false,
  },
  {
    id: 'primitive_shelter',
    name: 'Thatch Lean-To Shelter',
    era: 'primeval',
    description: 'Lash sturdy wooden branches and leafy thatch together to shield against bitter night winds.',
    icon: '🛖',
    requiredResearch: 110,
    researchProgress: 0,
    prerequisites: ['contained_hearth', 'flint_knapping'],
    requiredItems: { stick: 6, wood_log: 2 },
    unlocksBuildings: ['lean_to'],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'spear_hunting',
    name: 'Spear Hunting & Stalking',
    era: 'primeval',
    description: 'Learn to track wild rabbit trails and stalk grazing deer silently before striking with a flint spear.',
    icon: '🏹',
    requiredResearch: 120,
    researchProgress: 0,
    prerequisites: ['flint_knapping'],
    requiredItems: { flint: 1, stick: 1 },
    unlocksBuildings: [],
    unlocksItems: ['raw_meat', 'animal_hide', 'bone'],
    discovered: false,
  },
  {
    id: 'meat_roasting',
    name: 'Hearth Meat Roasting',
    era: 'primeval',
    description: 'Roast raw hunted game over campfire embers into succulent, hearty cooked meat that wards off starvation.',
    icon: '🍖',
    requiredResearch: 135,
    researchProgress: 0,
    prerequisites: ['spear_hunting', 'contained_hearth'],
    requiredItems: { raw_meat: 1, stick: 1 },
    unlocksBuildings: [],
    unlocksItems: ['cooked_meat'],
    discovered: false,
  },

  // ERA 2: NEOLITHIC & TRIBAL
  {
    id: 'fiber_weaving',
    name: 'Fiber Weaving',
    era: 'neolithic',
    description: 'Weave tough plant fibers into baskets to carry vastly more forage.',
    icon: '🧺',
    requiredResearch: 100,
    researchProgress: 0,
    prerequisites: ['primitive_shelter'],
    requiredItems: { stick: 4, wild_seeds: 2 },
    unlocksBuildings: [],
    unlocksItems: ['woven_basket'],
    discovered: false,
  },
  {
    id: 'clay_shaping',
    name: 'Clay Shaping & Pottery',
    era: 'neolithic',
    description: 'Scoop river clay and mold durable bowls and pots for storing water and seeds.',
    icon: '🏺',
    requiredResearch: 120,
    researchProgress: 0,
    prerequisites: ['contained_hearth'],
    requiredItems: { clay: 3 },
    unlocksBuildings: ['clay_kiln'],
    unlocksItems: ['clay_bowl', 'clay_pot', 'mud_brick'],
    discovered: false,
  },
  {
    id: 'wild_agriculture',
    name: 'Wild Agriculture',
    era: 'neolithic',
    description: 'Plant collected seeds in tilled soil for renewable, stable nourishment.',
    icon: '🌾',
    requiredResearch: 150,
    researchProgress: 0,
    prerequisites: ['flint_knapping', 'fiber_weaving'],
    requiredItems: { wild_seeds: 4, stick: 2 },
    unlocksBuildings: ['farm_plot'],
    unlocksItems: ['harvested_wheat'],
    discovered: false,
  },
  {
    id: 'mudbrick_architecture',
    name: 'Mudbrick Shelters',
    era: 'neolithic',
    description: 'Sun-dry clay and silt bricks to build sturdy dwellings that withstand rain.',
    icon: '🏠',
    requiredResearch: 200,
    researchProgress: 0,
    prerequisites: ['clay_shaping', 'primitive_shelter'],
    requiredItems: { mud_brick: 8, wood_log: 4 },
    unlocksBuildings: ['mud_hut', 'storage_barn'],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'wolf_domestication',
    name: 'Canine Domestication',
    era: 'neolithic',
    description: 'Befriend forest wolves with roasted meat, forging humanity\'s earliest bond with loyal domestic dogs.',
    icon: '🐕',
    requiredResearch: 220,
    researchProgress: 0,
    prerequisites: ['meat_roasting', 'primitive_shelter'],
    requiredItems: { cooked_meat: 2 },
    unlocksBuildings: [],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'animal_husbandry',
    name: 'Animal Husbandry & Shepherding',
    era: 'neolithic',
    description: 'Erect fenced wooden paddocks to shelter wild sheep, shearing thick wool for warm garments.',
    icon: '🐑',
    requiredResearch: 250,
    researchProgress: 0,
    prerequisites: ['wild_agriculture'],
    requiredItems: { stick: 8, wild_seeds: 4 },
    unlocksBuildings: ['animal_pen'],
    unlocksItems: ['raw_wool'],
    discovered: false,
  },

  // ERA 3: BRONZE & CRAFT
  {
    id: 'leather_tanning',
    name: 'Leather Tanning',
    era: 'bronze',
    description: 'Cure and scrape animal hides using stone scrapers to produce durable, supple leather.',
    icon: '🥋',
    requiredResearch: 280,
    researchProgress: 0,
    prerequisites: ['spear_hunting', 'clay_shaping'],
    requiredItems: { animal_hide: 3 },
    unlocksBuildings: [],
    unlocksItems: ['tanned_leather'],
    discovered: false,
  },
  {
    id: 'metallurgy_smelting',
    name: 'Copper Smelting',
    era: 'bronze',
    description: 'Extract bright metal from raw ore in high-heat kilns to forge superior tools.',
    icon: '⚒️',
    requiredResearch: 300,
    researchProgress: 0,
    prerequisites: ['clay_shaping', 'mudbrick_architecture'],
    requiredItems: { copper_ore: 4, firewood: 6 },
    unlocksBuildings: ['smelter', 'blacksmith'],
    unlocksItems: ['copper_ingot', 'copper_axe'],
    discovered: false,
  },
  {
    id: 'carpentry',
    name: 'Carpentry & Joinery',
    era: 'bronze',
    description: 'Saw and smooth timber into interlocking planks for multi-room wooden cabins.',
    icon: '🪵',
    requiredResearch: 350,
    researchProgress: 0,
    prerequisites: ['metallurgy_smelting'],
    requiredItems: { wood_log: 10, copper_axe: 1 },
    unlocksBuildings: ['thatched_cabin', 'timber_house'],
    unlocksItems: ['timber_plank'],
    discovered: false,
  },
  {
    id: 'stone_masonry',
    name: 'Stonemasonry & Wells',
    era: 'bronze',
    description: 'Chisel boulders into square blocks to dig deep wells for fresh drinking water.',
    icon: '🪨',
    requiredResearch: 400,
    researchProgress: 0,
    prerequisites: ['carpentry'],
    requiredItems: { stone: 12, mud_brick: 6 },
    unlocksBuildings: ['stone_well', 'masonry_house'],
    unlocksItems: ['cut_stone'],
    discovered: false,
  },

  // ERA 4: MEDIEVAL & TOWN
  {
    id: 'grain_milling',
    name: 'Grain Milling & Baking',
    era: 'medieval',
    description: 'Harness wind and grinding stones to mill wheat into fine flour for hearty bread.',
    icon: '🍞',
    requiredResearch: 500,
    researchProgress: 0,
    prerequisites: ['wild_agriculture', 'carpentry'],
    requiredItems: { harvested_wheat: 8, timber_plank: 6 },
    unlocksBuildings: ['windmill', 'bakery'],
    unlocksItems: ['flour', 'bread'],
    discovered: false,
  },
  {
    id: 'iron_working',
    name: 'Iron Forging',
    era: 'medieval',
    description: 'Smelt iron ore at blistering temperatures for heavy-duty tools and durable gears.',
    icon: '🗡️',
    requiredResearch: 600,
    researchProgress: 0,
    prerequisites: ['metallurgy_smelting'],
    requiredItems: { iron_ore: 6, firewood: 10 },
    unlocksBuildings: ['watchtower'],
    unlocksItems: ['iron_ingot', 'iron_tools'],
    discovered: false,
  },
  {
    id: 'commerce_and_markets',
    name: 'Commerce & Marketplaces',
    era: 'medieval',
    description: 'Establish designated trading stalls with fixed weights and fair exchange of goods.',
    icon: '⚖️',
    requiredResearch: 700,
    researchProgress: 0,
    prerequisites: ['grain_milling', 'iron_working'],
    requiredItems: { timber_plank: 10, bread: 5 },
    unlocksBuildings: ['market_stall'],
    unlocksItems: [],
    discovered: false,
  },

  {
    id: 'river_fishing',
    name: 'River Fishing & Trapping',
    era: 'primeval',
    description: 'Fashion woven wicker traps and bone hooks to catch freshwater fish swimming in rivers.',
    icon: '🐟',
    requiredResearch: 60,
    researchProgress: 0,
    prerequisites: ['discovery_wood'],
    requiredItems: { stick: 3 },
    unlocksBuildings: [],
    unlocksItems: ['fresh_fish', 'cooked_fish', 'fish_trap'],
    discovered: false,
  },
  {
    id: 'bridge_engineering',
    name: 'Bridge Engineering',
    era: 'neolithic',
    description: 'Construct sturdy timber footbridges across riverbeds to unite divided banks and expand exploration.',
    icon: '🌉',
    requiredResearch: 180,
    researchProgress: 0,
    prerequisites: ['primitive_shelter'],
    requiredItems: { wood_log: 4, stick: 6 },
    unlocksBuildings: ['wooden_bridge'],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'tailoring_insulation',
    name: 'Winter Cloaks & Insulation',
    era: 'neolithic',
    description: 'Stitch thick animal hides and wool fleece into insulated winter cloaks to brave freezing blizzards.',
    icon: '🧥',
    requiredResearch: 240,
    researchProgress: 0,
    prerequisites: ['fiber_weaving'],
    requiredItems: { animal_hide: 2, raw_wool: 2 },
    unlocksBuildings: [],
    unlocksItems: ['winter_cloak'],
    discovered: false,
  },
  {
    id: 'water_hydraulics',
    name: 'Water Hydraulics & Watermills',
    era: 'medieval',
    description: 'Harness flowing river currents with rotating paddle wheels to automate flour milling without manual toil.',
    icon: '⚙️',
    requiredResearch: 650,
    researchProgress: 0,
    prerequisites: ['grain_milling'],
    requiredItems: { timber_plank: 8, stone: 4 },
    unlocksBuildings: ['waterwheel'],
    unlocksItems: [],
    discovered: false,
  },
  {
    id: 'horse_whispering',
    name: 'Horse Whispering & Domestication',
    era: 'neolithic',
    description: 'Learn the calm gestures and sweet grains needed to approach wild horses, fashioning braided lassos and shelter paddocks.',
    icon: '🐎',
    requiredResearch: 150,
    researchProgress: 0,
    prerequisites: ['animal_domestication'],
    requiredItems: { raw_wool: 2, animal_hide: 1 },
    unlocksBuildings: ['horse_stable'],
    unlocksItems: ['braided_lasso'],
    discovered: false,
  },
  {
    id: 'wheel_and_cart',
    name: 'The Wheel & Cargo Carts',
    era: 'bronze',
    description: 'Carve solid wooden discs and axle joints to build 2-wheeled hauling carts that expand pioneer transport capacity tenfold.',
    icon: '🛒',
    requiredResearch: 320,
    researchProgress: 0,
    prerequisites: ['primitive_shelter'],
    requiredItems: { wood_log: 4, timber_plank: 4 },
    unlocksBuildings: [],
    unlocksItems: ['cargo_cart'],
    discovered: false,
  },
  {
    id: 'shipbuilding',
    name: 'Shipbuilding & Coastal Docks',
    era: 'bronze',
    description: 'Hollow out buoyant timber hulls and erect wooden harbor piers to sail across rivers and ocean waters.',
    icon: '⛵',
    requiredResearch: 380,
    researchProgress: 0,
    prerequisites: ['bridge_engineering'],
    requiredItems: { wood_log: 5, timber_plank: 4 },
    unlocksBuildings: ['dock_pier'],
    unlocksItems: ['wooden_boat'],
    discovered: false,
  },
  {
    id: 'written_language',
    name: 'Written Language & Archives',
    era: 'bronze',
    description: 'Inscribe symbolic pictographs and script onto cured vellum scrolls, preserving generational knowledge in a Great Archive.',
    icon: '📜',
    requiredResearch: 420,
    researchProgress: 0,
    prerequisites: ['clay_shaping'],
    requiredItems: { animal_hide: 2, stick: 4 },
    unlocksBuildings: ['great_library'],
    unlocksItems: ['written_scroll'],
    discovered: false,
  },
  {
    id: 'defensive_tactics',
    name: 'Palisades, Shields & Sentinels',
    era: 'bronze',
    description: 'Construct sharpened timber palisades and lockable gates, outfitting courageous sentinels with shields and hunting bows.',
    icon: '🛡️',
    requiredResearch: 350,
    researchProgress: 0,
    prerequisites: ['spear_hunting', 'flint_knapping'],
    requiredItems: { wood_log: 6, animal_hide: 2 },
    unlocksBuildings: ['timber_palisade', 'watch_gate'],
    unlocksItems: ['wooden_shield', 'hunting_bow'],
    discovered: false,
  },
  {
    id: 'aqueduct_engineering',
    name: 'Stone Aqueduct Engineering',
    era: 'medieval',
    description: 'Engineer elevated stone arch channels to carry fresh river water miles inland to irrigate town fields and cisterns.',
    icon: '🏛️',
    requiredResearch: 750,
    researchProgress: 0,
    prerequisites: ['masonry_construction', 'water_hydraulics'],
    requiredItems: { cut_stone: 8, mud_brick: 8 },
    unlocksBuildings: ['stone_aqueduct', 'water_cistern'],
    unlocksItems: [],
    discovered: false,
  },
  // ERA 5: RENAISSANCE & GOLDEN CITY
  {
    id: 'coin_minting',
    name: 'Coin Minting & Banking',
    era: 'renaissance',
    description: 'Smelt gold ore into uniform coins, establishing a universal currency and banking treasury.',
    icon: '🪙',
    requiredResearch: 900,
    researchProgress: 0,
    prerequisites: ['commerce_and_markets'],
    requiredItems: { gold_ore: 4, cut_stone: 12 },
    unlocksBuildings: ['mint_bank', 'town_hall'],
    unlocksItems: ['gold_coin'],
    discovered: false,
  },
  {
    id: 'civic_monuments',
    name: 'Civic Fountains & Pavements',
    era: 'renaissance',
    description: 'Paved cobblestone boulevards and marble fountains that turn a settlement into a glorious metropolis.',
    icon: '🏛️',
    requiredResearch: 1200,
    researchProgress: 0,
    prerequisites: ['coin_minting', 'stone_masonry'],
    requiredItems: { cut_stone: 20, gold_coin: 15 },
    unlocksBuildings: ['fountain'],
    unlocksItems: ['fine_clothes'],
    discovered: false,
  }
];

export const CRAFTING_RECIPES: CraftingRecipe[] = [
  {
    id: 'craft_firewood',
    name: 'Split Firewood',
    requiredTech: 'contained_hearth',
    inputs: { wood_log: 1 },
    output: 'firewood',
    outputCount: 3,
    timeCost: 4,
  },
  {
    id: 'craft_stone_axe',
    name: 'Craft Stone Axe',
    requiredTech: 'flint_knapping',
    inputs: { flint: 1, stick: 2 },
    output: 'stone_axe',
    outputCount: 1,
    timeCost: 4,
  },
  {
    id: 'craft_flint_spear',
    name: 'Craft Flint Spear',
    requiredTech: 'flint_knapping',
    inputs: { flint: 2, stick: 2 },
    output: 'flint_spear',
    outputCount: 1,
    timeCost: 5,
  },
  {
    id: 'craft_roast_meat',
    name: 'Roast Hunted Meat',
    requiredTech: 'meat_roasting',
    inputs: { raw_meat: 1, firewood: 1 },
    output: 'cooked_meat',
    outputCount: 1,
    timeCost: 4,
  },
  {
    id: 'craft_tanned_leather',
    name: 'Tan Animal Hide',
    requiredTech: 'leather_tanning',
    inputs: { animal_hide: 2 },
    output: 'tanned_leather',
    outputCount: 1,
    timeCost: 5,
  },
  {
    id: 'craft_basket',
    name: 'Weave Basket',
    requiredTech: 'fiber_weaving',
    inputs: { stick: 3, wild_seeds: 2 },
    output: 'woven_basket',
    outputCount: 1,
    timeCost: 4,
  },
  {
    id: 'craft_mud_brick',
    name: 'Bake Mud Brick',
    requiredTech: 'clay_shaping',
    inputs: { clay: 2, stick: 1 },
    output: 'mud_brick',
    outputCount: 2,
    timeCost: 3,
  },
  {
    id: 'craft_clay_pot',
    name: 'Throw Clay Pot',
    requiredTech: 'clay_shaping',
    inputs: { clay: 2 },
    output: 'clay_pot',
    outputCount: 1,
    timeCost: 3,
  },
  {
    id: 'craft_copper_ingot',
    name: 'Smelt Copper',
    requiredTech: 'metallurgy_smelting',
    inputs: { copper_ore: 2, firewood: 1 },
    output: 'copper_ingot',
    outputCount: 1,
    timeCost: 6,
  },
  {
    id: 'craft_copper_axe',
    name: 'Forge Copper Axe',
    requiredTech: 'metallurgy_smelting',
    inputs: { copper_ingot: 2, stick: 1 },
    output: 'copper_axe',
    outputCount: 1,
    timeCost: 5,
  },
  {
    id: 'craft_timber',
    name: 'Saw Timber Planks',
    requiredTech: 'carpentry',
    inputs: { wood_log: 1 },
    output: 'timber_plank',
    outputCount: 3,
    timeCost: 3,
  },
  {
    id: 'craft_cut_stone',
    name: 'Chisel Cut Stone',
    requiredTech: 'stone_masonry',
    inputs: { stone: 2 },
    output: 'cut_stone',
    outputCount: 2,
    timeCost: 4,
  },
  {
    id: 'craft_flour',
    name: 'Mill Grain to Flour',
    requiredTech: 'grain_milling',
    inputs: { harvested_wheat: 2 },
    output: 'flour',
    outputCount: 2,
    timeCost: 3,
  },
  {
    id: 'craft_bread',
    name: 'Bake Fresh Bread',
    requiredTech: 'grain_milling',
    inputs: { flour: 1, firewood: 1 },
    output: 'bread',
    outputCount: 2,
    timeCost: 4,
  },
  {
    id: 'craft_iron_ingot',
    name: 'Smelt Iron Ingot',
    requiredTech: 'iron_working',
    inputs: { iron_ore: 2, firewood: 2 },
    output: 'iron_ingot',
    outputCount: 1,
    timeCost: 7,
  },
  {
    id: 'craft_iron_tools',
    name: 'Forge Iron Tools',
    requiredTech: 'iron_working',
    inputs: { iron_ingot: 2, timber_plank: 1 },
    output: 'iron_tools',
    outputCount: 1,
    timeCost: 6,
  },
  {
    id: 'craft_gold_coin',
    name: 'Mint Gold Coins',
    requiredTech: 'coin_minting',
    inputs: { gold_ore: 1, firewood: 1 },
    output: 'gold_coin',
    outputCount: 5,
    timeCost: 5,
  },
  {
    id: 'craft_fish_trap',
    name: 'Weave Wicker Fish Trap',
    requiredTech: 'river_fishing',
    inputs: { stick: 4, wild_seeds: 2 },
    output: 'fish_trap',
    outputCount: 1,
    timeCost: 4,
  },
  {
    id: 'cook_fish',
    name: 'Roast River Fish',
    requiredTech: 'contained_hearth',
    inputs: { fresh_fish: 1, firewood: 1 },
    output: 'cooked_fish',
    outputCount: 1,
    timeCost: 3,
  },
  {
    id: 'craft_winter_cloak',
    name: 'Tailor Insulated Winter Cloak',
    requiredTech: 'tailoring_insulation',
    inputs: { animal_hide: 2, raw_wool: 2 },
    output: 'winter_cloak',
    outputCount: 1,
    timeCost: 6,
  },
  {
    id: 'craft_braided_lasso',
    name: 'Weave Braided Lasso',
    requiredTech: 'horse_whispering',
    inputs: { raw_wool: 2, animal_hide: 1 },
    output: 'braided_lasso',
    outputCount: 1,
    timeCost: 4,
  },
  {
    id: 'craft_cargo_cart',
    name: 'Assemble Cargo Cart',
    requiredTech: 'wheel_and_cart',
    inputs: { wood_log: 2, timber_plank: 2 },
    output: 'cargo_cart',
    outputCount: 1,
    timeCost: 8,
  },
  {
    id: 'craft_wooden_boat',
    name: 'Carve Wooden Boat',
    requiredTech: 'shipbuilding',
    inputs: { wood_log: 3, timber_plank: 2 },
    output: 'wooden_boat',
    outputCount: 1,
    timeCost: 9,
  },
  {
    id: 'craft_written_scroll',
    name: 'Inscribe Scroll',
    requiredTech: 'written_language',
    inputs: { animal_hide: 1, wild_seeds: 1 },
    output: 'written_scroll',
    outputCount: 1,
    timeCost: 5,
  },
  {
    id: 'craft_wooden_shield',
    name: 'Craft Wooden Shield',
    requiredTech: 'defensive_tactics',
    inputs: { timber_plank: 2, animal_hide: 1 },
    output: 'wooden_shield',
    outputCount: 1,
    timeCost: 6,
  },
  {
    id: 'craft_hunting_bow',
    name: 'Carve Hunting Bow',
    requiredTech: 'defensive_tactics',
    inputs: { stick: 3, raw_wool: 1 },
    output: 'hunting_bow',
    outputCount: 1,
    timeCost: 5,
  }
];

export const BUILDING_SPECS: Record<BuildingType, BuildingCost> = {
  campfire: {
    type: 'campfire',
    name: 'Contained Campfire & Hearth',
    description: 'A ring of river stones containing glowing embers, providing radiant warmth and night light.',
    requiredTech: 'contained_hearth',
    inputs: { stick: 4, stone: 4 },
    workNeeded: 25,
    maxWorkers: 2,
    maxStorage: 20,
    housingCapacity: 0,
  },
  lean_to: {
    type: 'lean_to',
    name: 'Thatched Lean-To',
    description: 'Basic shelter shielding pioneers from cold and wind.',
    requiredTech: 'primitive_shelter',
    inputs: { stick: 8, wood_log: 2 },
    workNeeded: 35,
    maxWorkers: 2,
    maxStorage: 30,
    housingCapacity: 2,
  },
  mud_hut: {
    type: 'mud_hut',
    name: 'Mudbrick Hut',
    description: 'Durable residential hut allowing family expansion.',
    requiredTech: 'mudbrick_architecture',
    inputs: { mud_brick: 8, wood_log: 3 },
    workNeeded: 60,
    maxWorkers: 3,
    maxStorage: 50,
    housingCapacity: 4,
  },
  farm_plot: {
    type: 'farm_plot',
    name: 'Irrigated Farm Plot',
    description: 'Regularly produces abundant harvested wheat.',
    requiredTech: 'wild_agriculture',
    inputs: { wild_seeds: 4, stick: 4 },
    workNeeded: 40,
    maxWorkers: 2,
    maxStorage: 60,
    production: {
      outputs: { harvested_wheat: 4 },
      interval: 80,
    }
  },
  clay_kiln: {
    type: 'clay_kiln',
    name: 'Clay Kiln',
    description: 'Bakes bricks and pots quickly.',
    requiredTech: 'clay_shaping',
    inputs: { clay: 6, stone: 4 },
    workNeeded: 50,
    maxWorkers: 2,
    maxStorage: 40,
  },
  animal_pen: {
    type: 'animal_pen',
    name: 'Fenced Animal Pen',
    description: 'Enclosed wooden paddock for domestic sheep, periodically producing harvested wool.',
    requiredTech: 'animal_husbandry',
    inputs: { stick: 10, wood_log: 4 },
    workNeeded: 65,
    maxWorkers: 2,
    maxStorage: 60,
    production: {
      outputs: { raw_wool: 2 },
      interval: 100,
    }
  },
  storage_barn: {
    type: 'storage_barn',
    name: 'Storage Barn',
    description: 'Massive central storage for settlement surplus.',
    requiredTech: 'mudbrick_architecture',
    inputs: { mud_brick: 12, wood_log: 8 },
    workNeeded: 80,
    maxWorkers: 4,
    maxStorage: 300,
    housingCapacity: 0,
  },
  thatched_cabin: {
    type: 'thatched_cabin',
    name: 'Thatched Log Cabin',
    description: 'Warm, comfortable timber home for growing families.',
    requiredTech: 'carpentry',
    inputs: { timber_plank: 10, stone: 4 },
    workNeeded: 90,
    maxWorkers: 3,
    maxStorage: 80,
    housingCapacity: 5,
  },
  stone_well: {
    type: 'stone_well',
    name: 'Freshwater Well',
    description: 'Infinite clean water source for hydration and farms.',
    requiredTech: 'stone_masonry',
    inputs: { cut_stone: 8, timber_plank: 2 },
    workNeeded: 70,
    maxWorkers: 2,
    maxStorage: 50,
  },
  smelter: {
    type: 'smelter',
    name: 'Foundry Smelter',
    description: 'Smelts raw ores into copper and iron ingots.',
    requiredTech: 'metallurgy_smelting',
    inputs: { stone: 10, clay: 6 },
    workNeeded: 100,
    maxWorkers: 2,
    maxStorage: 100,
  },
  blacksmith: {
    type: 'blacksmith',
    name: 'Blacksmith Forge',
    description: 'Forges metal tools, axes, and construction nails.',
    requiredTech: 'metallurgy_smelting',
    inputs: { cut_stone: 10, timber_plank: 6, copper_ingot: 2 },
    workNeeded: 120,
    maxWorkers: 2,
    maxStorage: 120,
  },
  windmill: {
    type: 'windmill',
    name: 'Grain Windmill',
    description: 'Automatically grinds wheat into flour.',
    requiredTech: 'grain_milling',
    inputs: { timber_plank: 16, cut_stone: 6 },
    workNeeded: 140,
    maxWorkers: 2,
    maxStorage: 150,
    production: {
      inputs: { harvested_wheat: 2 },
      outputs: { flour: 3 },
      interval: 60,
    }
  },
  bakery: {
    type: 'bakery',
    name: 'Town Bakery',
    description: 'Bakes golden loaves of bread in bulk.',
    requiredTech: 'grain_milling',
    inputs: { cut_stone: 12, mud_brick: 8 },
    workNeeded: 120,
    maxWorkers: 3,
    maxStorage: 120,
    production: {
      inputs: { flour: 2, firewood: 1 },
      outputs: { bread: 4 },
      interval: 70,
    }
  },
  timber_house: {
    type: 'timber_house',
    name: 'Timber Townhouse',
    description: 'Spacious two-story residence for citizens.',
    requiredTech: 'carpentry',
    inputs: { timber_plank: 16, cut_stone: 6 },
    workNeeded: 130,
    maxWorkers: 3,
    maxStorage: 100,
    housingCapacity: 6,
  },
  masonry_house: {
    type: 'masonry_house',
    name: 'Cobblestone Manor',
    description: 'Luxurious stone home providing high happiness and safety.',
    requiredTech: 'stone_masonry',
    inputs: { cut_stone: 20, timber_plank: 12 },
    workNeeded: 160,
    maxWorkers: 4,
    maxStorage: 150,
    housingCapacity: 8,
  },
  market_stall: {
    type: 'market_stall',
    name: 'Marketplace Plaza',
    description: 'Hub for trade, exchange of commodities, and coin transactions.',
    requiredTech: 'commerce_and_markets',
    inputs: { timber_plank: 12, cut_stone: 6 },
    workNeeded: 150,
    maxWorkers: 4,
    maxStorage: 400,
  },
  mint_bank: {
    type: 'mint_bank',
    name: 'Mint & City Bank',
    description: 'Mints coins, manages treasury loans, and stabilizes inflation.',
    requiredTech: 'coin_minting',
    inputs: { cut_stone: 24, timber_plank: 16, copper_ingot: 4 },
    workNeeded: 220,
    maxWorkers: 3,
    maxStorage: 500,
  },
  town_hall: {
    type: 'town_hall',
    name: 'Grand City Hall',
    description: 'Civic headquarters governing city expansion, taxes, and celebrations.',
    requiredTech: 'coin_minting',
    inputs: { cut_stone: 30, timber_plank: 24, gold_coin: 10 },
    workNeeded: 300,
    maxWorkers: 5,
    maxStorage: 1000,
    housingCapacity: 4,
  },
  watchtower: {
    type: 'watchtower',
    name: 'Defense Watchtower',
    description: 'Expands fog of war radius and safeguards citizens.',
    requiredTech: 'iron_working',
    inputs: { timber_plank: 14, cut_stone: 8, iron_tools: 1 },
    workNeeded: 110,
    maxWorkers: 2,
    maxStorage: 50,
  },
  fountain: {
    type: 'fountain',
    name: 'Marble City Fountain',
    description: 'Great civic monument bringing awe, pride, and high happiness to citizens.',
    requiredTech: 'civic_monuments',
    inputs: { cut_stone: 28, gold_coin: 15 },
    workNeeded: 250,
    maxWorkers: 4,
    maxStorage: 50,
  },
  ancestral_cairn: {
    type: 'ancestral_cairn',
    name: 'Ancestral Memorial Cairn',
    description: 'A sacred stone cairn commemorating passed ancestors, bringing peace and reverence to family descendants.',
    requiredTech: 'contained_hearth',
    inputs: { stone: 6, wild_seeds: 2 },
    workNeeded: 20,
    maxWorkers: 2,
    maxStorage: 20,
    housingCapacity: 0,
  },
  settlement_totem: {
    type: 'settlement_totem',
    name: 'Settlement Entrance Totem',
    description: 'A hand-carved wooden gateway marking the territory and founding name of the pioneer village.',
    requiredTech: 'primitive_shelter',
    inputs: { wood_log: 2, stick: 4 },
    workNeeded: 30,
    maxWorkers: 2,
    maxStorage: 10,
    housingCapacity: 0,
  },
  wooden_bridge: {
    type: 'wooden_bridge',
    name: 'Wooden River Footbridge',
    description: 'Sturdy timber log walkway spanning over water, allowing pioneers, animals, and carts to cross rivers.',
    requiredTech: 'bridge_engineering',
    inputs: { wood_log: 3, stick: 4 },
    workNeeded: 35,
    maxWorkers: 2,
    maxStorage: 0,
    housingCapacity: 0,
  },
  waterwheel: {
    type: 'waterwheel',
    name: 'River Waterwheel Mill',
    description: 'A riverside water-powered mill whose rotating paddles harness water currents to automatically process harvested wheat into fine flour.',
    requiredTech: 'water_hydraulics',
    inputs: { timber_plank: 10, stone: 6, iron_tools: 1 },
    workNeeded: 90,
    maxWorkers: 2,
    maxStorage: 80,
    housingCapacity: 0,
    production: {
      inputs: { harvested_wheat: 1 },
      outputs: { flour: 2 },
      interval: 15,
    },
  },
  horse_stable: {
    type: 'horse_stable',
    name: 'Equine Timber Stable',
    description: 'A spacious wooden stable with hay mangers and stalls to shelter and breed domesticated horses.',
    requiredTech: 'horse_whispering',
    inputs: { wood_log: 6, timber_plank: 4, raw_wool: 2 },
    workNeeded: 50,
    maxWorkers: 2,
    maxStorage: 40,
    housingCapacity: 0,
  },
  dock_pier: {
    type: 'dock_pier',
    name: 'Shoreline Harbor Dock',
    description: 'A weathered wooden boardwalk pier jutting out over water for mooring boats and embarking on voyages.',
    requiredTech: 'shipbuilding',
    inputs: { timber_plank: 6, wood_log: 3 },
    workNeeded: 40,
    maxWorkers: 2,
    maxStorage: 40,
    housingCapacity: 0,
  },
  great_library: {
    type: 'great_library',
    name: 'Great Archive & Library',
    description: 'A grand stone repository of scrolls, philosophy, and history, accelerating technological research.',
    requiredTech: 'written_language',
    inputs: { cut_stone: 12, timber_plank: 8, written_scroll: 2 },
    workNeeded: 120,
    maxWorkers: 3,
    maxStorage: 100,
    housingCapacity: 0,
  },
  timber_palisade: {
    type: 'timber_palisade',
    name: 'Sharpened Timber Palisade',
    description: 'A sturdy wall of sharpened logs protecting the settlement perimeter from predators.',
    requiredTech: 'defensive_tactics',
    inputs: { wood_log: 2, stick: 2 },
    workNeeded: 15,
    maxWorkers: 1,
    maxStorage: 0,
    housingCapacity: 0,
  },
  watch_gate: {
    type: 'watch_gate',
    name: 'Fortified Watch Gate',
    description: 'A crenellated wooden gatehouse manned by settlement sentinels to monitor incoming travelers.',
    requiredTech: 'defensive_tactics',
    inputs: { wood_log: 4, timber_plank: 2 },
    workNeeded: 35,
    maxWorkers: 2,
    maxStorage: 10,
    housingCapacity: 0,
  },
  stone_aqueduct: {
    type: 'stone_aqueduct',
    name: 'Stone Aqueduct Arch',
    description: 'Elevated stone flume carrying fresh water from rivers to automatically irrigate nearby farm plots.',
    requiredTech: 'aqueduct_engineering',
    inputs: { cut_stone: 4, mud_brick: 4 },
    workNeeded: 45,
    maxWorkers: 2,
    maxStorage: 0,
    housingCapacity: 0,
  },
  water_cistern: {
    type: 'water_cistern',
    name: 'Central Water Cistern',
    description: 'A deep stone reservoir that stores fresh water, ensuring crops survive even in dry summers.',
    requiredTech: 'aqueduct_engineering',
    inputs: { cut_stone: 6, clay: 4 },
    workNeeded: 50,
    maxWorkers: 2,
    maxStorage: 50,
    housingCapacity: 0,
  }
};
